controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_showmenu:
  path: /showmenu/{semaine_year}
  defaults:
    semaine_year: today
  controller: App\Controller\MenuController::showmenu


app_editmenu:
  path: /editmenu/{semaine_year}
  defaults:
    semaine_year: today
  controller: App\Controller\MenuController::editmenu  

# google_connect:
#     path: /connexion/google
#     controller: knpu.oauth2.controller.authenticator:connectAction
#     guard: true